# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 619)
        Dialog.setStyleSheet("background-color: #111111;\n"
"color: #EEEEEE;\n"
"border-radius: 15px;\n"
"font: 15pt \"Cantarell\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.settings = QtWidgets.QWidget()
        self.settings.setStyleSheet("padding: 10px;\n"
"margin: 5px;")
        self.settings.setObjectName("settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(parent=self.settings)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.settings)
        self.lineEdit.setStyleSheet("background-color: #333333;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.settings)
        self.lineEdit_2.setStyleSheet("background-color: #333333;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.settings)
        self.plainTextEdit.setStyleSheet("background-color: #333333;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.radioButton = QtWidgets.QRadioButton(parent=self.settings)
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton.setStyleSheet("background-color: #333333;")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.settings)
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton_2.setStyleSheet("background-color: #333333;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.settings)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #333333;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.settings)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #333333;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.settings)
        self.profile = QtWidgets.QWidget()
        self.profile.setStyleSheet("padding: 10px;\n"
"margin: 5px;")
        self.profile.setObjectName("profile")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.profile)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.profile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(300, 300))
        self.label_3.setSizeIncrement(QtCore.QSize(1, 1))
        self.label_3.setStyleSheet("padding: 00px;\n"
"margin: 0px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/misc/profile.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.frame = QtWidgets.QFrame(parent=self.profile)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser.setStyleSheet("background-color: #333333;")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setStyleSheet("background-color: #333333;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #333333;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("background-color: #333333;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.stackedWidget.addWidget(self.profile)
        self.newcontact = QtWidgets.QWidget()
        self.newcontact.setStyleSheet("padding: 10px;\n"
"margin: 5px;")
        self.newcontact.setObjectName("newcontact")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.newcontact)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(parent=self.newcontact)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.newcontact)
        self.lineEdit_4.setStyleSheet("background-color: #333333;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.newcontact)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_4.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #333333;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #222222;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_5.addWidget(self.pushButton_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.newcontact)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Dialog)
        self.pushButton_3.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "TextLabel"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Name"))
        self.plainTextEdit.setPlaceholderText(_translate("Dialog", "Bio"))
        self.radioButton.setText(_translate("Dialog", "Dark Theme"))
        self.radioButton_2.setText(_translate("Dialog", "Light Theme"))
        self.pushButton_2.setText(_translate("Dialog", "Change photo"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">asdf</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">asdf</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_3.setText(_translate("Dialog", "Close"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Username"))
        self.pushButton_4.setText(_translate("Dialog", "Add"))
